# roles/docker/tasks/main.yml
---
- name: Installing required Python module
  pip:
    name: docker-py
    state: present

- name: Deploying application
  docker_container:
    name: "{{ docker_name }}"
    image: "{{ docker_image }}"
    pull: yes
    state: started
    restart: yes
    ports:
      - 80:8080
    env:
      ADMINER_DEFAULT_SERVER: "{{ rds_address }}"
